apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80 # Public port
      targetPort: 3000 # Container port
  type: LoadBalancer # To expose the frontend publicly
