apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  labels:
    app: node-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
        - name: node-backend-container
          image: node:18-alpine
          ports:
            - containerPort: 3000 # Or the port your backend uses
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/mydb" # Assuming mongodb-service is your MongoDB Kubernetes Service name