apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
spec:
  selector:
    app: node-backend
  ports:
    - protocol: TCP
      port: 3000 # Internal port
      targetPort: 3000
  type: ClusterIP # Only accessible within the cluster