apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest # Or a specific version
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config # You'll need a ConfigMap as well
        - name: prometheus-data
          emptyDir: {} # Or use a PersistentVolumeClaim for persistent storage
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec: